### ISSUE TITLE
What about trying HoundCI again?

### ISSUE THREAD

**Issue by erino** [withassociates/with-pair#55]
If so we should ignore a few checks, such as:

```yml
Style/LineLength:
  Max: 120

Style/StringLiterals:
  Enabled: false
```
